config/routes.rb
AmazonS3Browser::Application.routes.draw do

  get "welcome/index"

  resources :profiles

  devise_for :users

  root :to => "welcome#index"

  match ':controller/:action'
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  # GET /profiles
  # GET /profiles.xml
  def index
    @profile = Profile.find(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
    @profile = Profile.new(params[:profile])
    @profile.user_id = 1

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :s3_key %><br />
    <%= f.text_field :s3_key %>
  </div>
  <div class="field">
    <%= f.label :s3_secret %><br />
    <%= f.text_field :s3_secret %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

 <%= simple_form_for @profile do |f| %>
    <%= f.input :s3_key %>
    <%= f.input :s3_secret %>
    <%= f.association :user %>
    <%= f.button :submit %>
  <% end %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table align=center>
  <tr>
    <th>S3 key</th>
    <th>S3 secret</th>
    <th></th>

  </tr>


  <tr>
    <td><%= @profile.s3_key %></td>
    <td><%= @profile.s3_secret %></td>

    <td><%= link_to 'Edit', edit_profile_path(@profile.id) %></td>

  </tr>

</table>

<br />

app/views/profiles/new.html.erb
<h1>New profile</h1>

 <%= simple_form_for @profile do |f| %>
    <%= f.input :s3_key %>
    <%= f.input :s3_secret %>
    <%= f.association :user %>
    <%= f.button :submit %>
  <% end %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>S3 key:</b>
  <%= @profile.s3_key %>
</p>

<p>
  <b>S3 secret:</b>
  <%= @profile.s3_secret %>
</p>

<p>
  <b>User:</b>
  <%= @profile.user %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>